### PR TITLE
Fix uncaught HTTP exception

### PR DESCRIPTION
**Pull request by ricardopereira**
- should always enqueue the callback block

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Not sure I understand why this change is needed, @tcard over to you

**Comment by ricardopereira** [comment]
@mattheworiordan I fixed it because it was raising an exception when a request was returning 500 ([see here](https://github.com/ably/ably-ios/pull/289/files#diff-6decbd6ac2aba5822e5b35c79f08d353L85)). It was calling the callback ([here](https://github.com/ably/ably-ios/pull/289/files#diff-6decbd6ac2aba5822e5b35c79f08d353L88)) without enqueuing the block on the current loop.

BTW, the sandbox seems to be unstable.

**Comment by mattheworiordan** [comment]
> BTW, the sandbox seems to be unstable.

Yes, we are oddly getting an unstable sandbox quite frequently.  I will ask Paddy to fix it now, sorry

**Comment by ricardopereira** [comment]
And with this bug (all night on this one 😅) I found out that the `[xcpretty](https://github.com/supermarin/xcpretty)` ignores abnormal failures, consequently the log hangs and Travis kills the process. I reproduce it successfully: https://github.com/ricardopereira/CrashTestSuiteExample.

**Comment by mattheworiordan** [comment]
> And with this bug (all night on this one 😅) I found out that the xcpretty ignores abnormal failures, 

Well done finding that one!

**Comment by tcard** [comment]
LGTM

**Pull request merged**
