### PR TITLE
RTN17a

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by tcard** [comment]
To be revisited after #385 is merged.

**Comment by mattheworiordan** [comment]
👍

**Comment by tcard** [comment]
PTAL

**Comment by mattheworiordan** [comment]
👍

**Comment by tcard** [comment]
The fix used to pass but now it crashes, I guess because of some conflict with what got merged to master in the meantime. I'll merge this and #388, #390, #444 and #406 just with pending tests, without the fixes, and then do a separate PR fixing all of them together, to avoid conflicting fixes between them.

**Pull request merged**
