### PR TITLE
Update develop branch with master

### PR DESCRIPTION
**Pull request by ricardopereira**
Can't update `develop` manually:

```
➜  ably-ios git:(develop) git push origin develop
Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 1.59 KiB | 1.59 MiB/s, done.
Total 7 (delta 5), reused 0 (delta 0)
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/develop.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/ably/ably-ios.git
 ! [remote rejected]   develop -> develop (protected branch hook declined)
error: failed to push some refs to 'https://github.com/ably/ably-ios.git'
```

### CODE REVIEW

**Comment by mattheworiordan** [comment]
@ricardopereira please confirm when released so that @tomczoink can notify the customer.

**Comment by paddybyers** [comment]
We should be raising PRs against `develop`, and reviewing them and merging them into `develop`.

`master` should only ever be a fast-forward to a commit in `develop`, without a further merge commit.

New commits should not be introduced in a PR into `develop` from `master`.

**Comment by funkyboy** [comment]
@ricardopereira see 
https://github.com/ably/ably-ios#release-process

**Comment by ricardopereira** [comment]
You're right. I did a mistake. I wanted to release a version with the same code base of v1.1.0 but I was dumb. I don't wanted to to include develop changes. I should be in `develop`, checkout the `1.1.0` tag and do the changes, right?

**Comment by paddybyers** [comment]
> I don't wanted to to include develop changes

So this is a hotfix release that doesn't include other changes that are already merged into `develop` ?

In that case, create a new branch from the last release tag (`hotfix-release-1.1.1` or whatever), and open PRs with your changes against that branch. We will review and merge them. Then, once you're happy to make that release:

1 tag the branch with the new release version;
2 make the release;
3 fast-forward `master` to that commit;
4 merge that commit into `develop`

If github won't allow you to do (3), then we will update the permissions to allow you to do that.

**Comment by ricardopereira** [comment]
> So this is a hotfix release that doesn't include other changes that are already merged into develop ?

Exactly.

The only thing I missed was _create a new branch from the last release tag (hotfix-release-1.1.1 or whatever)_. I create the branch with `master` last commit.

And I couldn't `merge that commit into develop`, that's why I did this PR.

**Pull request merged**
