### PR TITLE
RTN3

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by mattheworiordan** [comment]
@ricardopereira why don't you base your PR on an existing PR?  This PR includes commits from other PRs unnecessarily, it should only include the commits relating to this PR.  When you create a PR, you can chose to base it off another PR.  Please do this in future to remove unnecessary duplication so that people reviewing the PRs are only reviewing the relevant commits

**Comment by ricardopereira** [comment]
> @ricardopereira why don't you base your PR on an existing PR? This PR includes commits from other PRs unnecessarily, it should only include the commits relating to this PR. When you create a PR, you can chose to base it off another PR. Please do this in future to remove unnecessary duplication so that people reviewing the PRs are only reviewing the relevant commits

Didn't no. I will do that for now on.

**Comment by mattheworiordan** [comment]
This looks good, is it ready for merge, or do you have any other points to address?

**Comment by ricardopereira** [comment]
@mattheworiordan It's ready. Thank you.

**Pull request merged**
