### PR TITLE
RSC15e as a part of 0.9

### PR DESCRIPTION
**Pull request by EvgenyKarkan**
Please review and merge if everything looks good.

### CODE REVIEW

**Comment by EvgenyKarkan** [comment]
Please review and merge if everything looks good.

**Comment by EvgenyKarkan** [comment]
@mattheworiordan I was sure that test for what you describing [already exists](https://github.com/ably/ably-ios/blob/master/Spec/RestClient.swift#L618-L648), no?
In my PR I only added test for custom rest host, to be sure that request will try it instead of default `rest.ably.io`. 
Could you please take a look again, do I still need any changes here?

**Comment by mattheworiordan** [comment]
> In my PR I only added test for custom rest host, to be sure that request will try it instead of default rest.ably.io. 

But I am not really clear why this test is needed then given providing a custom `restHost` is covered in many places, including of course http://docs.ably.io/client-lib-development-guide/features/#TO3k2.  We know that restHost is used by those tests, so I am not clear what we are achieving then if a test for http://docs.ably.io/client-lib-development-guide/features/#TO3k2 already exists?

Can you explain as I feel like we're just duplicating tests unnecessarily now?

**Comment by EvgenyKarkan** [comment]
You are right, I see that there are couple of places to test overridden `restHost`.
But please understand me, I just wanted to test it after I read this diff from 0.8:
`(unless overriden in ClientOptions#restHost)`.
So I will close this useless PR, thanks for the feedback @mattheworiordan. :)

**Comment by mattheworiordan** [comment]
Ok, no problem. I am hoping to set up a call with Dmitry and all of you shortly so that we can discuss next steps as perhaps some guidance of expected test coverage would be sensible moving forwards.

**Comment by EvgenyKarkan** [comment]
Closed as discussed above.

**Pull request closed without merging**
