### PR TITLE
RTN18a

### PR DESCRIPTION
**Pull request by ricardopereira**
✅ Passing

### CODE REVIEW

**Comment by mattheworiordan** [comment]
LGTM

**Comment by ricardopereira** [comment]
It is important to merge #169 first, rebase with master and check if it is ok.

**Comment by ricardopereira** [comment]
@tcard I run the complete test suite and it's failing with:

```
RestClient__initializer__should_accept_a_token_UsersricardopereiraRepositoriesWhitesmithablyiosablySpecRestClientswift_48, failed - Got error 'Error Domain=io.ably.cocoa Code=40100 "" UserInfo={ARTErrorStatusCode=401, NSLocalizedDescription=, NSLocalizedFailureReason=invalid credentials}'
/Users/ricardopereira/Repositories/Whitesmith/ably-ios/ablySpec/TestUtilities.swift:215
```

```
RestClient__initializer__should_accept_a_token_UsersricardopereiraRepositoriesWhitesmithablyiosablySpecRestClientswift_48, failed - expected to eventually be nil, got <Error Domain=io.ably.cocoa Code=40100 "" UserInfo={ARTErrorStatusCode=401, NSLocalizedDescription=, NSLocalizedFailureReason=invalid credentials}>
/Users/ricardopereira/Repositories/Whitesmith/ably-ios/ablySpec/RestClient.swift:51
```

The tests were passing when you implemented the `initWithToken`? Or are they missing the `pending`?

**Comment by tcard** [comment]
> The tests were passing when you implemented the initWithToken?

On my machine, yes. I run them again against master and it's still happily passing. Weird...

**Pull request merged**
