### PR TITLE
Xcode 7.2 (use xcodebuild)

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by tcard** [comment]
Well, this one doesn't seem to have stalled. LGTM, let's see if this proves more stable, although I'm a bit skeptical since it was stalling also before we were using `scan`...

**Comment by ricardopereira** [comment]
```
Failing tests:
	-[ARTRestInitTest testInitWithKey]
	-[RealtimeClientChannel Channel__should_process_all_incoming_messages_and_presence_messages_as_soon_as_a_Channel_becomes_attached()]
	-[RestClient RestClient__logging__should_output_to_the_system_log_and_the_log_level_should_be_Warn()]
	-[RestClientChannels RestClient__channels__releaseChannel__should_release_a_channel()]
```

@tcard Can we merge #253? It fixes the log error.

I will check the `testInitWithKey` and `Channel__should_process_all_incoming_messages_and_presence_messages_as_soon_as_a_Channel_becomes_attached`.

**Comment by tcard** [comment]
@ricardopereira @253 is missing @mattheworiordan 's LGTM.

**Comment by mattheworiordan** [comment]
Sorry for the delay, but LGTM. Will review #253 now

**Pull request merged**
