### PR TITLE
RTS2

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by ricardopereira** [comment]
@tcard Maybe it is best to change the `ARTRealtime.channels` function to a property to have a nice Swift integration: `client.channels()["test"]` -> `client.channels["test"]`.

**Comment by mattheworiordan** [comment]
FYI, the documented API is `client.channels.get('name')` not `client.channel('name')`.  The latter is a nice to have and supported in some libraries.

**Comment by ricardopereira** [comment]
Ok, it is possible and easy to add an extension to NSDictionary with categories (`get`).

**Comment by tcard** [comment]
I'd rather just stick to the API on this one. This is one of the issues listed in #140, I'll fix it soon.

**Comment by tcard** [comment]
To be clear, I mean that I'd rather use a custom collection class than to add stuff to NSDictionary. Just for the sake of simplicity and keeping the API minimal. E. g. if we add a `get` method now we'd have `get` and `objectForKey` to do the same thing.

**Comment by ricardopereira** [comment]
Rebased with no changes.

**Comment by ricardopereira** [comment]
Can I merge this?

**Comment by tcard** [comment]
Yep, sorry.

**Pull request merged**
