### PR TITLE
Rename AblyRealtime to Ably

### PR DESCRIPTION
**Pull request by ricardopereira**
- [x] Tests
 - [x] Example project
 - [x] Push new pod

### CODE REVIEW

**Comment by ricardopereira** [comment]
```
target 'AblyClientApp' do
  pod 'Ably'
end
```

Tested the CocoaPod 'Ably' with Swift and Objective-C.

Import like
 - **Swift:**
```
import Ably
```

 - **Objective-C**
```
#import <Ably/Ably.h>
```

**Comment by ricardopereira** [comment]
⚠️ Create a new release from tag `0.8.6` after this has been merged.

**Comment by mattheworiordan** [comment]
Tasks:

* [ ] Merge in all other PRs before this release so 0.8 is complete, ideally with Reauth but we can do that after
* [ ] Create a new release from tag 0.8.6 after this has been merged.
* [ ] Update all references in documentation
* [ ] Update README
* [ ] Update CHANGELOG with important notice about the change.

**Comment by mattheworiordan** [comment]
@tcard I may need your help with this on Monday

**Comment by mattheworiordan** [comment]
@ricardopereira it does not look like all the tasks is this PR are going to be done, so please can you create a new issue now with those tasks so that we get those bits done?

**Comment by ricardopereira** [comment]
@mattheworiordan Ok, I will.

**Pull request merged**
