### PR TITLE
Fix: memory leak when publishing via realtime

### PR DESCRIPTION
**Pull request by ricardopereira**
#625

### CODE REVIEW

**Comment by ricardopereira** [comment]
An attempt to mislead the problem.

**Comment by mattheworiordan** [comment]
@ricardopereira unfortunately not sure I can comment on this.  Will have to rely on @tcard here

**Comment by tcard** [comment]
I'm not really sure what is this. Is this WIP?

**Comment by ricardopereira** [comment]
@tcard The client should try this with `pod 'Ably', :git => 'https://github.com/ably/ably-ios.git', :branch => 'fix-625'` and see if it helps.. I turned off the additional log data for Sentry.

**Pull request closed without merging**
