### PR TITLE
RTN15h

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by mattheworiordan** [comment]
LGTM

**Comment by tcard** [comment]
I don't think this test is right. It should be like [RTN14b](https://github.com/ably/ably-ios/blob/bc22daea6906a675d54ab9a84f4c861e13056e55/Spec/RealtimeClientConnection.swift#L1379), whose spec is exactly the same except it's an ERROR ProtocolMessage instead of DISCONNECTED. I'll adapt it.

**Comment by tcard** [comment]
PTAL

**Comment by ricardopereira** [comment]
👍

**Pull request merged**
