### PR TITLE
Swift tests: RSC7, RSC18

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Looks good, but the commits for RSC9 and RSC10 are already merged so this PR has included additional commits I think?

**Comment by ricardopereira** [comment]
@mattheworiordan The RSC9 and RSC10 commits come from the PR that you merged: `#70 - Swift tests: RSC9`. I joined RSC9 and RSC10 to the same branch.

**Comment by mattheworiordan** [comment]
@ricardopereira the thing is that your branch `swift-tests-RSC7` should only contain the commits for this PR.  If commits from another PR are included in this branch, then the scope of this PR becomes greater than what you intended.  Why don't you rebase this on master and force push this branch, and only the relevant commits will be included, and I can then merge.

**Comment by ricardopereira** [comment]
@mattheworiordan Then I misunderstood, sorry. In some PRs I needed the changes of the last PR so I created each PR to merge with the last one.

So, what am I missing?
Before each push spec-branch I need to rebase it with master and create the PR to merge with the master branch?

**Comment by mattheworiordan** [comment]
> Then I misunderstood, sorry. In some PRs I needed the changes of the last PR so I created each PR to merge with the last one.

It's not really that important to be honest, and I could just merge it so sorry if I am being pedantic.  But the idea generally is as follows:

```
master
  |-> feature A (2 commits)
       -> feature B (2 commits)
```

So when you do a PR for feature A it will contain only 2 commits, and be based from master i.e. the from bit of the PR in Github.  You do not push the 2 commits from feature B into the feature A branch, so that feature A will only have the 2 commits relating to feature A.

When you then do a PR for feature B because A is not yet merged, you do the pull request from A to B and once again this only has 2 commits, and the PR only has the 2 commits relevant to the feature.

Does that make sense?

**Comment by ricardopereira** [comment]
@mattheworiordan
> When you then do a PR for feature B because A is not yet merged, **you do the pull request from A to B** and once again this only has 2 commits, and the PR only has the 2 commits relevant to the feature.

But that is what I do. E.g. The last one I created:
screen_shot_2015-11-18_at_10_57_08

**Comment by mattheworiordan** [comment]
Mm, I now see the issue.  Apologies for the confusion, but glad I understand why this happened.

Looking at the branch `swift-tests-RSC7` at https://github.com/ably/ably-ios/commits/swift-tests-RSC7, I can see commit 82db599afd3febeff9cdc6e0f00e14d8540e4ea7 which is what I expect to see in this branch (and I expect what you have in your local branch).  However I also see dc48ada0f930f8cc2dee260d5182076238797421 and f71fb9ae1caf80748cf39687f4ba7fd4592616ef.  These two commits shouldn't be in this branch.  Looking then at the merge commit f4f606a155158c22f4a2acfab6f3b690a0a162fc for PR https://github.com/ably/ably-ios/pull/70, I can see that #70 was merged before this branch was merged, and as such the commits from that branch are added to this branch.

So I am not really sure how to get around this problem other than to ensure I merge in PRs in the order they were issued so that we don't end up adding commits from a later PR into an earlier PR that it is based on.  

Sorry once again for the confusion, let's try and stick to a rule that PRs based on others should be merged after the parent PR is merged.

**Comment by ricardopereira** [comment]
@mattheworiordan I agree. I thought about it and I don't see other way than to ensure the merging order.

**Pull request closed without merging**
