### PR TITLE
RTN7a

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by ricardopereira** [comment]
@mattheworiordan What is the best approach to test `NACK` action?

**Comment by ricardopereira** [comment]
Needs #128

**Comment by mattheworiordan** [comment]
Few comments, but not sure they are relevant to this PR necessarily and could be separate issues.

**Comment by mattheworiordan** [comment]
I think this PR needs to deal with `NACK` before it is merged in, please add support

**Comment by ricardopereira** [comment]
@mattheworiordan @tcard Ready to be reviewed.

**Comment by mattheworiordan** [comment]
Nice, LGTM :+1:

**Comment by tcard** [comment]
LGTM

**Pull request merged**
