### PR TITLE
Bitrise CI

### PR DESCRIPTION
**Pull request by ricardopereira**
[Bitrise.io](http://bitrise.io) is also free and has a great support service.

### CODE REVIEW

**Comment by ricardopereira** [comment]
I will try this: http://devcenter.bitrise.io/docs/step-hangs-times-out-after-a-period-without-any-logs-on-bitrise

**Comment by tcard** [comment]
I don't see how any of those can apply to our case. Anyway, can't you try this on a separate branch?

**Comment by ricardopereira** [comment]
Yes, I can but you're right. I was wondering if the scheme was `shared` and it is. Any other doesn't apply.

**Comment by ricardopereira** [comment]
Have you faced any stalled build after #265?

**Comment by tcard** [comment]
@ricardopereira None so far.

**Comment by ricardopereira** [comment]
Me too.
Many builds are failing because of this:
```
-[RestClientChannels RestClient__channels__releaseChannel__should_release_a_channel()]
```

**Comment by mattheworiordan** [comment]
I don't care which CI we use, however I would be surprised if Travis is at fault here.  If Bitrise works though, then we should move across.

**Comment by ricardopereira** [comment]
@mattheworiordan No, Bitrise is failing too.
Before this PR I updated the Travis server with the latest stable version of Xcode and removed `scan`. Currently, the test suite is executed with the standard xcodebuild command.

**Comment by ricardopereira** [comment]
So, currently the test suite seems to be fine. We run a couple of tests and none of them hanged.
I read that `xcpretty` (used by `scan`) seems to be buggy with the latest Xcode versions but like @tcard said the test suite was hanging before the `scan` was introduced so maybe the new Xcode version solved it. From the release notes:
> Fixed in Xcode 7.2.1:
• Command line tool ‘xcodebuild test’ will no longer time out waiting for Simulator.app to launch

I will close this and get back to the priority list.

**Pull request closed without merging**
