### PR TITLE
Separate BaseMessage private parts.

### PR DESCRIPTION
**Pull request by tcard**
Plus, remove useless content method.

### CODE REVIEW

**Comment by tcard** [comment]
Tests are failing because of #198 and #199. Will rebase this one once those are merged and should be passing then.

**Comment by ricardopereira** [comment]
You need to add the `ARTBaseMessage+Private.h` to the private modulemap.

**Comment by ricardopereira** [comment]
LGTM

**Comment by mattheworiordan** [comment]
LGTM

**Comment by tcard** [comment]
Rebased plus e09104ad7b5a52e68cdb940a77af810be9750cb9, what @ricardopereira said.

**Pull request merged**
