### PR TITLE
Travis enhancements

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by ricardopereira** [comment]
I did a little optimisation. If the first test target fails then it will stop the test suite immediately.
@mattheworiordan @tcard PTAL. I want to merge this.

**Comment by mattheworiordan** [comment]
>  I want to merge this.

And I'm watching [the build](https://travis-ci.org/ably/ably-ios/builds/113623972) :)

**Comment by ricardopereira** [comment]
Unfortunately, the log will only update in the end of the execution 😞 but at least the test suite will be more stable... I hope so 😁

**Comment by ricardopereira** [comment]
The `AblySpec` target failed and the `AblyTests` didn't start :+1:
@mattheworiordan Can I run the test again and see if it passes?

**Comment by tcard** [comment]
I'm not sure this is a good idea. I want to know all the tests I'm breaking so that I can fix all of them.

**Comment by ricardopereira** [comment]
But it takes time and you will know all the failing tests from the current test target.

**Comment by ricardopereira** [comment]
>> I'm not sure this is a good idea. I want to know all the tests I'm breaking so that I can fix all of them.

> @tcard But it takes time and you will know all the failing tests from the current test target.

@mattheworiordan What is your opinion about this?

**Comment by mattheworiordan** [comment]
>> But it takes time and you will know all the failing tests from the current test target.

> What is your opinion about this?

I am not sure I understand the problem.  Are you saying we don't get the list of broken tests in the output?  Generally, I prefer for a build not to abort and run all tests so that when you get the feedback, you can go through all broken tests, fix them and rebuild.  If we abort a test early, won't it then prevent this?  Why was 81eca60  needed?

**Comment by ricardopereira** [comment]
@mattheworiordan We have two steps: `AblySpec` (Swift) and `AblyTests` (ObjC). I did 81eca60 in case of one of the steps fails, the test suite stops immediately and is marked as errored. It will show all the broken tests about the current step.

**Comment by ricardopereira** [comment]
Sorry, I didn't mention why I did it. Well, I thought it would be nice to abort the test suite immediately if one of the steps fails to win time but maybe it makes more sense to have a clear idea on what it's failing.

**Comment by ricardopereira** [comment]
Ok, I will undo 81eca60.

**Comment by ricardopereira** [comment]
I decided to do a new commit to maintain the old ones in the history. Could be helpful for something else.

**Comment by ricardopereira** [comment]
@mattheworiordan @tcard Can I merge?

**Comment by tcard** [comment]
Yes, LGTM.

**Pull request merged**
