### PR TITLE
RTL7b

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by tcard** [comment]
LGTM

**Comment by mattheworiordan** [comment]
LGTM

**Comment by ricardopereira** [comment]
:facepalm: I shouldn't have merged.

**Comment by mattheworiordan** [comment]
> :facepalm: I shouldn't have merged.

Why not?

**Comment by ricardopereira** [comment]
Because I wanted to rebase it first after #204.

**Pull request merged**
