### PR TITLE
Project rename: ably to Ably

### PR DESCRIPTION
**Pull request by ricardopereira**
#143

### CODE REVIEW

**Comment by tcard** [comment]
LGTM

**Comment by ricardopereira** [comment]
**`xcodebuild -workspace ./ably.xcworkspace -list` output:**
```
Information about workspace "ably":
    Schemes:
        Ably
        AblyTests
        AblySpec
        Aspects
        Nimble
        Pods
        Pods-AblySpec
        Pods-AblyTests
        Quick
        SwiftWebSocket
        SwiftyJSON
```

**Comment by mattheworiordan** [comment]
LGTM, does it build locally?

**Comment by ricardopereira** [comment]
@mattheworiordan Yes and using it with CocoaPods is also working.

**Comment by mattheworiordan** [comment]
Excellent

**Pull request merged**
