### PR TITLE
RSC10, RSC14c: Adapt to new spec, 40140 -> [40140, 40150).

### PR DESCRIPTION
**Pull request by tcard**
https://github.com/ably/docs/commit/b628023b83aca480464d55e4260e21ee20690d7a

Because the CI is currently pretty much useless, I'll leave this here:

captura de pantalla 2016-01-22 a les 18 24 29

### CODE REVIEW

**Comment by tcard** [comment]
@ricardopereira All PRs should be rebased on top of this once it's merged, or tests won't pass.

**Comment by ricardopereira** [comment]
LGTM

**Comment by tcard** [comment]
@mattheworiordan Merging because it's a bit annoying to have this one blocked.

**Comment by mattheworiordan** [comment]
LGTM, sorry for the delay @tcard

**Pull request merged**
