### PR TITLE
Remove pending from RestClientStats

### PR DESCRIPTION
**Pull request by ricardopereira**
#142

### CODE REVIEW

**Comment by mattheworiordan** [comment]
LGTM, but not passing?

**Comment by ricardopereira** [comment]
Yes, both failed with: `Channel__subscribe__should_exist_ensuring_published_messages_are_not_echoed_back_to_the_subscriber_when_echoMessages_is_false, failed - Waited more than 10.0 seconds`

Will check.

**Comment by tcard** [comment]
I don't think this will just work now. Remember that this happened intermittently, with an off-by-one error, which suggests something related to timing, like some events being recorded in the stats in the next interval than expected. Nothing has changed that would prevent that, AFAIK.

**Comment by ricardopereira** [comment]
I think it's more than that. The problem is affecting all the test suite. All the current PRs aren't passing with this similar problem: tests failing intermitently. I'm catching all of those fails to see any relation between them: #283. The CI is quite useless with this problem. It's really frustrating.

**Comment by tcard** [comment]
That's a different issue @ricardopereira, I'm talking specifically about the stats tests.

**Comment by mattheworiordan** [comment]
FYI @ricardopereira, sandbox was a bit unstable in the last 24 hours or so so could have been contributing to this.

**Comment by ricardopereira** [comment]
Lets see if we get fails from `stats` and then I analyse what could be wrong.

**Pull request merged**
