### PR TITLE
RSA8b

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Partial support, spec says `... which override defaults for Client Auth`.  There is no test that it overrides any defaults, so you should set those defaults such as clientId in the `ClientOptions`, and ensure that the options are overriden here.

**Comment by ricardopereira** [comment]
@mattheworiordan Yes you right. But I do not see anything more than the `clientId` to override.

**Comment by mattheworiordan** [comment]
> Yes you right. But I do not see anything more than the clientId to override

You can override any defaults, so if after calling `authorise` with a set of TokenParams (which it supports and uses for defaults for subsequent requests), you can test that not overriding them uses the defaults, and overriding them uses the new TokenParams

**Comment by ricardopereira** [comment]
@mattheworiordan Done

**Comment by mattheworiordan** [comment]
LGTM

**Pull request merged**
