### PR TITLE
Update ULID version

### PR DESCRIPTION
**Pull request by funkyboy**
Note: [failures like this](https://travis-ci.org/ably/ably-ios/jobs/414123320#L996) are obviously due to Travis not being up to date with the pod repos.
I'd not add a `pod repo update` command, because that can increase further the build time. 

UPDATE: this PR is on hold. See 
https://github.com/ably/ably-ios/pull/769#issuecomment-418772286

### CODE REVIEW

**Comment by ricardopereira** [comment]
Oh boy 😄 So we can't merge this until Travis updates his macOS image with latest pod updates, right?

**Comment by funkyboy** [comment]
@ricardopereira Correct. I'll wait. It's not an urgent change.

**Comment by funkyboy** [comment]
@ricardopereira talked to support. Unfortunately this is the only way at the moment https://github.com/ably/ably-ios/pull/769/commits/2077e83b3c15b5c06645174dc356b6dd80ad67f0 :(

**Comment by funkyboy** [comment]
@ricardopereira this is ready for another look. Tests are green.

**Comment by paddybyers** [comment]
If this is being put on hold, can you edit the title please to make that clear?

**Pull request closed without merging**
