### PR TITLE
Fix compiler warnings.

### PR DESCRIPTION
**Pull request by tcard**
Mostly about using NSInteger in formatted strings, which the compiler dislikes.

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Looks good, although Travis build stalled?

**Comment by tcard** [comment]
@mattheworiordan The CI build is broken right now (#143). It just stalls sometimes. We talked about this at the standup (I thought @ricardopereira said he would write it down). He has tried out this weekend Circe CI and something else and it still stalls there, so there must be something wrong with our build script or whatever. We agreed that fixing this is non-trivial and low priority right now, as we are only three people looking at PRs and we can just trust each other that the test suite passes in our machines for now. What do you think?

**Comment by mattheworiordan** [comment]
> It just stalls sometimes.

I do recall that discussion, however I understood we had a potential solution.  I did not realise this issue was still present.

I agree it's not the highest priority, but it is an issue.  Do we have an issue for it?

**Comment by ricardopereira** [comment]
Yes, we have. The issue is #143.

**Comment by ricardopereira** [comment]
LGTM

**Pull request merged**
