### PR TITLE
Fix format of section

### PR DESCRIPTION
**Pull request by funkyboy**

### CODE REVIEW

**Comment by ricardopereira** [comment]
Thanks. Could you add some info on how to run the test suite?

**Comment by funkyboy** [comment]
@ricardopereira Still trying to figure that part out :)

**Comment by ricardopereira** [comment]
@funkyboy Sorry about that 😖 Please check the travis file: https://github.com/ably/ably-ios/blob/7227d57e33c5caedcf6404c72cbd7e391ae8870e/.travis.yml#L20

I forgot to add those steps in the README.

**Comment by funkyboy** [comment]
@ricardopereira added instructions.

**Pull request merged**
