### PR TITLE
Actually test RSA8c1.

### PR DESCRIPTION
**Pull request by tcard**
The test was left incomplete. It didn't check the GET query nor
the headers.

### CODE REVIEW

**Comment by tcard** [comment]
Failing due to #143, can't break Obj-C tests, should be considered passing.

**Comment by mattheworiordan** [comment]
LGTM :+1:

**Comment by ricardopereira** [comment]
LGTM

**Comment by ricardopereira** [comment]
Please, do not merge. I want to test it on my machine.

**Pull request merged**
