### PR TITLE
RTL10a

### PR DESCRIPTION
**Pull request by ricardopereira**
[Review on Reviewable](https://reviewable.io/reviews/ably/ably-ios/229)

### CODE REVIEW

**Comment by ricardopereira** [comment]
Did 31db95f because of this strange conversion:
screen shot 2016-02-16 at 15 27 57

 - Changed `historyWithError` with just `history`.

**Comment by tcard** [comment]
I think a more definitive test would be to use Aspects to check that calling Realtime's history calls Rest's history. It's hard to completely test "Supports all the same params" otherwise; you would have to check what happens if you remove some, if they do the same, etc.

**Comment by ricardopereira** [comment]
> I think a more definitive test would be to use Aspects to check that calling Realtime's history calls Rest's history. It's hard to completely test "Supports all the same params" otherwise; you would have to check what happens if you remove some, if they do the same, etc.

@tcard Done

**Comment by tcard** [comment]
LGTM

**Comment by mattheworiordan** [comment]
:+1:

**Pull request merged**
