### PR TITLE
Fix RTN14b test.

### PR DESCRIPTION
**Pull request by tcard**

### CODE REVIEW

**Comment by tcard** [comment]
I just realized this is missing: "If the token creation fails, the next connection attempt fails again due to a token error [...] the connection will transition to the FAILED state and the Connection#errorReason will be set". Will do soon.

**Comment by ricardopereira** [comment]
LGTM

**Comment by ricardopereira** [comment]
@mattheworiordan PTAL

**Comment by mattheworiordan** [comment]
NIce, LGTM

**Pull request merged**
