### PR TITLE
Payload data either as a JSON Object or Array

### PR DESCRIPTION
**Pull request by ricardopereira**
#97

### CODE REVIEW

**Comment by mattheworiordan** [comment]
LGTM

**Comment by tcard** [comment]
LGTM as well.

Why didn't you merge this already?

**Comment by ricardopereira** [comment]
I'm waiting for the call.

**Comment by tcard** [comment]
Oh, OK. I thought LGTM basically meant "you can merge this".

**Comment by ricardopereira** [comment]
Well, maybe it does :smile: I'm not familiar with LGTM

**Comment by mattheworiordan** [comment]
LGTM means Looks Good To Me, so yes, @tcard is right, good to merge

**Pull request merged**
