### PR TITLE
Travis: Xcode 7.3

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by tcard** [comment]
LGTM

**Comment by tcard** [comment]
Merging right away to see if this fixes anything...

**Comment by tcard** [comment]
Well, no, it even fails to compile SwiftWebSocket.

**Comment by mattheworiordan** [comment]
Yup, unfortunately this seems to have made things worse in regards to a stable CI build

**Comment by ricardopereira** [comment]
Xcode 7.3 beta use Swift v2.2.
SwiftWebSocket has a different branch for the new version so it's not stable.
I will close this.

**Pull request closed without merging**
