### PR TITLE
CI: update CocoaPod to v1.0.1

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by mattheworiordan** [comment]
LGTM

**Comment by ricardopereira** [comment]
Just for the record. This build failed because of:

```
[09:09:12]: ▸ Testing failed:
[09:09:12]: ▸ Test target AblyTests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
[09:09:12]: ▸ Failing tests:
[09:09:12]: ▸ -[RealtimeClientPresence Presence__subscribe__with_no_arguments_should_subscribe_a_listener_to_all_presence_messages()]
[09:09:12]: ▸ -[RealtimeClientPresence Presence__leave__should_leave_the_current_client_with_no_data()]
[09:09:12]: ▸ -[RealtimeClientPresence Presence__enter__should_result_in_an_error_if_the_client_does_not_have_required_presence_permission()]
[09:09:12]: ▸ -[RealtimeClientPresence Presence__update__should_result_in_an_error_if_the_client_does_not_have_required_presence_permission()]
[09:09:12]: ▸ -[RealtimeClientPresence Presence__leave__should_result_in_an_error_if_the_client_does_not_have_required_presence_permission()]
[09:09:12]: ▸ -[RealtimeClientPresence Presence__enter__should_emit_the_data_attribute_in_the_LEAVE_event_when_data_is_provided_when_entering_but_no_data_is_provided_when_leaving()]
[09:09:12]: ▸ -[RealtimeClientPresence Presence__history__should_return_a_PaginatedResult_page()]
[09:09:12]: ▸ -[RealtimeClientPresence Presence__history__should_return_a_PaginatedResult_page()]
[09:09:12]: ▸ -[RestClientPresence Presence__presence_messages_retrieved_are_decoded_in_the_same_way_that_messages_are_decoded()]
[09:09:12]: ▸ ** TEST FAILED **
```

Nothing related with this PR. Can be merged.

**Comment by mattheworiordan** [comment]
Worrying that it failed though, but I agree, can be merged. Will wait for @tcard to confirm

**Comment by tcard** [comment]
The errors are either the know issue with presence leave data, or something like this: `expected to contain <Channel denied access based on given capability>, got <Invalid clientId for credentials>` which should be investigated but it's arguably not crucial as it's failing as expected, just not for the expected reason.

Then it seems that we have some crashes in `Presence__history__should_return_a_PaginatedResult_page` and `Presence__presence_messages_retrieved_are_decoded_in_the_same_way_that_messages_are_decoded`. Not test assertion failures, but crashes, e. g. nil pointer exceptions or things like that. The tests for the most part don't stop when a precondition fails, so they then hit paths that crash, like this:

```swift
waitUntil(done) {
    channel.attach { error
        if error != nil {
            fail("error not nil")
            done(); return
        }
        done()
    }
}

// if error wasn't nil, we really should stop the test execution here

channel.doSomethingAssumingItsAttached()
```

And the iOS test runner doesn't even let us see the `"error not nil"` message if the test crashes, so it's hard to diagnose from Travis, and it can be hard to reproduce then on Xcode with better diagnostics because the precondition failing most of the times is due to a transient error.

So I would just make sure that the crashing tests pass individually, which I'd bet they do. Arguably it's also not critical right now to make the tests more resilient to crashes.

**Comment by mattheworiordan** [comment]
> So I would just make sure that the crashing tests pass individually, which I'd bet they do. Arguably it's also not critical right now to make the tests more resilient to crashes.

Well @tcard I agree we don't need to make them more resilient to crashes, but I do think we need a stable test suite so that the work being done by Prophonix is on a solid base.  Therefore if I see a PR which fails I will know that is most likely due to a real failure.

@ricardopereira I am happy to merge this, but please raise any issues necessary to describe the CI problems so that we can get these resolved.

PS. Presence issues should be fixed on Sandbox now, but I am testing using the Ruby lib to be sure.

**Comment by ricardopereira** [comment]
A stable test suite is critical at this point. For example with #444: it has a core change which affects the complete client. When I run the test suite and I see a couple of errors where it's difficult to understand if it's an Ably service error or a code mistake or even a race condition then I'm not comfortable to say it's ready to be merged.

I will open an issue with all the frustrations I'm facing and what I do to override them. Could be important to discuss and decide what should be done.

**Comment by mattheworiordan** [comment]
> I will open an issue with all the frustrations I'm facing and what I do to override them. Could be important to discuss and decide what should be done.

Thanks

**Comment by ricardopereira** [comment]
Running failed tests individually:

```
[09:09:12]: ▸ Failing tests:
✅ [09:09:12]: ▸ -[RealtimeClientPresence Presence__subscribe__with_no_arguments_should_subscribe_a_listener_to_all_presence_messages()]
✅ [09:09:12]: ▸ -[RealtimeClientPresence Presence__leave__should_leave_the_current_client_with_no_data()]
❌ [09:09:12]: ▸ -[RealtimeClientPresence Presence__enter__should_result_in_an_error_if_the_client_does_not_have_required_presence_permission()]
Failed with: expected to contain <Channel denied access based on given capability>, got <Invalid clientId for credentials>
❌ [09:09:12]: ▸ -[RealtimeClientPresence Presence__update__should_result_in_an_error_if_the_client_does_not_have_required_presence_permission()]
Failed with: expected to contain <Channel denied access based on given capability>, got <Invalid clientId for credentials>
❌ [09:09:12]: ▸ -[RealtimeClientPresence Presence__leave__should_result_in_an_error_if_the_client_does_not_have_required_presence_permission()]
Failed with: expected to contain <Channel denied access based on given capability>, got <Invalid clientId for credentials>
✅ [09:09:12]: ▸ -[RealtimeClientPresence Presence__enter__should_emit_the_data_attribute_in_the_LEAVE_event_when_data_is_provided_when_entering_but_no_data_is_provided_when_leaving()]
❌ [09:09:12]: ▸ -[RealtimeClientPresence Presence__history__should_return_a_PaginatedResult_page()]
Failed with: expected to all pass a condition, but failed first at element ...
❌ [09:09:12]: ▸ -[RestClientPresence Presence__presence_messages_retrieved_are_decoded_in_the_same_way_that_messages_are_decoded()]
Failed with: expected to equal <{test = 1;}>, got <nil>
```

**Comment by tcard** [comment]
All of these are about a known issue with presence LEAVE in the backend.

**Comment by tcard** [comment]
Sorry, except for the "Invalid clientId for credentials" ones. That might have to do with 0ed5bb98097b12c5f03673556f073580a6720d01.

**Comment by tcard** [comment]
@ricardopereira Anything blocking this?

**Comment by ricardopereira** [comment]
@tcard No. Can be merged.

**Pull request merged**
