### PR TITLE
RTN10b

### PR DESCRIPTION
**Pull request by ricardopereira**
Not passing.

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Ok, looks good.

**Comment by ricardopereira** [comment]
Rebased with changes.

Connection serial isn't set to -1 when a new connection is opened: `expected to equal <-1>, got <0>`.
Should I open an issue?

**Comment by mattheworiordan** [comment]
> Should I open an issue?

We should discuss at our stand up today what we do with pull requests with tests that fail.  I am concerned that if we merge them in we are only compounding the problem of our unreliable test suite.  One to discuss later

**Comment by tcard** [comment]
LGTM

We agreed on marking those as pending, right?

**Comment by ricardopereira** [comment]
Yes, after two _LGTM_.

**Pull request merged**
