### PR TITLE
RTN12a

### PR DESCRIPTION
**Pull request by ricardopereira**
Not passing. I think the transport is not waiting for the ProtocolMessage.Closed action (final step).

### CODE REVIEW

**Comment by tcard** [comment]
The test looks good to me.

**Comment by mattheworiordan** [comment]
LGTM :+1:

**Comment by ricardopereira** [comment]
Rebased with no changes.

> Not passing. I think the transport is not waiting for the ProtocolMessage.Closed action (final step).

Should I open an issue and rebase this PR or it remains open until the fix is implemented?

**Comment by tcard** [comment]
Can you mark this as pending so we can merge?

**Pull request merged**
