### PR TITLE
Connection proxy

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Can we add some tests to ensure the properties are actually available in the API?

**Comment by ricardopereira** [comment]
That is what I'm doing now.

**Comment by mattheworiordan** [comment]
Any luck with the tests so that we can merge this PR?

**Comment by ricardopereira** [comment]
@mattheworiordan This PR only has the `ARTConnection` proxy but I started the spec implementation on #44.

**Pull request merged**
